<?php namespace smp_verified_profiles;

function register_verified_profile_custom_fields()
{

	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}



    $verified_profile_settings = get_verified_profile_settings();
    $verified_profile_settings_slug = $verified_profile_settings["slug"]; 


	acf_add_local_field_group( array(
	'key' => 'group_67e39e4171b16',
	'title' => 'Verified Profile',
	'fields' => array(
		array(
			'key' => 'field_67e47e841bef5',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67e39e414527f',
			'label' => 'Featured',
			'name' => 'featured',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_67e3a0f205af6',
			'label' => 'URL',
			'name' => 'url',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key'          => 'field_67e3a10405af7',
					'label'        => 'Wikipedia',
					'name'         => 'wikipedia',
					'aria-label'   => '',
					'type'         => 'text',
					'instructions' => 'url_wikipedia [get_profile_field field="url_wikipedia"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e3a10b05af8',
					'label'        => 'Facebook',
					'name'         => 'facebook',
					'type'         => 'text',
					'instructions' => 'url_facebook [get_profile_field field="url_facebook"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e3a11305af9',
					'label'        => 'Instagram',
					'name'         => 'instagram',
					'type'         => 'text',
					'instructions' => 'url_instagram [get_profile_field field="url_instagram"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e3a11a05afa',
					'label'        => 'LinkedIn',
					'name'         => 'linkedin',
					'type'         => 'text',
					'instructions' => 'url_linkedin [get_profile_field field="url_linkedin"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f1',
					'label'        => 'Website',
					'name'         => 'website',
					'type'         => 'text',
					'instructions' => 'url_website [get_profile_field field="url_website"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f2',
					'label'        => 'SoundCloud',
					'name'         => 'soundcloud',
					'type'         => 'text',
					'instructions' => 'url_soundcloud [get_profile_field field="url_soundcloud"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f3',
					'label'        => 'IMDB',
					'name'         => 'imdb',
					'type'         => 'text',
					'instructions' => 'url_imdb [get_profile_field field="url_imdb"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f4',
					'label'        => 'TikTok',
					'name'         => 'tiktok',
					'type'         => 'text',
					'instructions' => 'url_tiktok [get_profile_field field="url_tiktok"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f5',
					'label'        => 'YouTube',
					'name'         => 'youtube',
					'type'         => 'text',
					'instructions' => 'url_youtube [get_profile_field field="url_youtube"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f6',
					'label'        => 'Amazon',
					'name'         => 'amazon',
					'type'         => 'text',
					'instructions' => 'url_amazon [get_profile_field field="url_amazon"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f7',
					'label'        => 'X',
					'name'         => 'x',
					'type'         => 'text',
					'instructions' => 'url_x [get_profile_field field="url_x"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f8',
					'label'        => 'Audible',
					'name'         => 'audible',
					'type'         => 'text',
					'instructions' => 'url_audible [get_profile_field field="url_audible"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588f9',
					'label'        => 'GitHub',
					'name'         => 'github',
					'type'         => 'text',
					'instructions' => 'url_github [get_profile_field field="url_github"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588fa',
					'label'        => 'F6S',
					'name'         => 'f6s',
					'type'         => 'text',
					'instructions' => 'url_f6s [get_profile_field field="url_f6s"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588fb',
					'label'        => 'Crunchbase',
					'name'         => 'crunchbase',
					'type'         => 'text',
					'instructions' => 'url_crunchbase [get_profile_field field="url_crunchbase"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588fc',
					'label'        => 'Muckrack',
					'name'         => 'muckrack',
					'type'         => 'text',
					'instructions' => 'url_muckrack [get_profile_field field="url_muckrack"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
				array(
					'key'          => 'field_67e4a6ee588fd',
					'label'        => 'AngelList',
					'name'         => 'angellist',
					'type'         => 'text',
					'instructions' => 'url_angellist [get_profile_field field="url_angellist"]',
					'required'     => 0,
					'conditional_logic' => 0,
					'wrapper'      => array('width'=>'','class'=>'','id'=>''),
					'default_value'=> '',
					'maxlength'    => '',
					'allow_in_bindings' => 0,
					'placeholder'  => '',
					'prepend'      => '',
					'append'       => '',
				),
			),
		),
		
		array(
			'key' => 'field_67e4d7f8ed086',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67fa08231bd34',
			'label' => 'Biography',
			'name' => 'biography',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_67fa082b1bd35',
			'label' => 'Biography Short',
			'name' => 'biography_short',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => $verified_profile_settings_slug,
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );


}