<?php namespace smp_verified_profiles;
/*
register_acf_fields_general()
register_acf_post_type_profile()
*/

//DEELTE THIS FILE

function register_acf_post_type_profile()
{
    add_action('init', __NAMESPACE__ . '\\register_verified_profile_cpt');
    function register_verified_profile_cpt() {
        // pull ACF options (fallback to defaults)
        $singular = function_exists('get_field')
            ? get_field('verified_profile_name_singular','option') ?: 'Verified Profile'
            : 'Verified Profile';
        $plural = function_exists('get_field')
            ? get_field('verified_profile_name_plural','option') ?: 'Verified Profiles'
            : 'Verified Profiles';
        $slug = function_exists('get_field')
            ? get_field('verified_profile_slug','option') ?: 'profile'
            : 'profile';
    
        $labels = array(
            'name'                  => $plural,
            'singular_name'         => $singular,
            'menu_name'             => $plural,
            'all_items'             => "All $plural",
            'edit_item'             => "Edit $singular",
            'view_item'             => "View $singular",
            'view_items'            => "View $plural",
            'add_new_item'          => "Add New $singular",
            'add_new'               => "Add New $singular",
            'new_item'              => "New $singular",
            'parent_item_colon'     => "Parent $singular:",
            'search_items'          => "Search $plural",
            'not_found'             => "No $plural found",
            'not_found_in_trash'    => "No $plural found in Trash",
            'archives'              => "$singular Archives",
            'attributes'            => "$singular Attributes",
            'insert_into_item'      => "Insert into $singular",
            'uploaded_to_this_item' => "Uploaded to this $singular",
            'filter_items_list'     => "Filter $plural list",
            'filter_by_date'        => "Filter $plural by date",
            'items_list_navigation' => "$plural list navigation",
            'items_list'            => "$plural list",
            'item_published'        => "$singular published.",
            'item_published_privately'=> "$singular published privately.",
            'item_reverted_to_draft'=> "$singular reverted to draft.",
            'item_scheduled'        => "$singular scheduled.",
            'item_updated'          => "$singular updated.",
            'item_link'             => "$singular Link",
            'item_link_description' => "A link to a $singular.",
        );
    
        register_post_type($slug, array(
            'labels'             => $labels,
            'public'             => true,
            'show_in_rest'       => true,
            'rewrite'            => array('slug'=>$slug),
            'supports'           => array('title','author','trackbacks','editor','excerpt','revisions','page-attributes','thumbnail','custom-fields','post-formats'),
            'taxonomies'         => array('category','post_tag'),
            'delete_with_user'   => false,
        ));
    }
    
	register_post_type( 'Xprofile', array(
	'labels' => array(
		'name' => 'Verified Profiles',
		'singular_name' => 'Profile',
		'menu_name' => 'Verified Profiles',
		'all_items' => 'All Verified Profiles',
		'edit_item' => 'Edit Profile',
		'view_item' => 'View Profile',
		'view_items' => 'View Verified Profiles',
		'add_new_item' => 'Add New Profile',
		'add_new' => 'Add New Profile',
		'new_item' => 'New Profile',
		'parent_item_colon' => 'Parent Profile:',
		'search_items' => 'Search Verified Profiles',
		'not_found' => 'No verified profiles found',
		'not_found_in_trash' => 'No verified profiles found in Trash',
		'archives' => 'Profile Archives',
		'attributes' => 'Profile Attributes',
		'insert_into_item' => 'Insert into profile',
		'uploaded_to_this_item' => 'Uploaded to this profile',
		'filter_items_list' => 'Filter verified profiles list',
		'filter_by_date' => 'Filter verified profiles by date',
		'items_list_navigation' => 'Verified Profiles list navigation',
		'items_list' => 'Verified Profiles list',
		'item_published' => 'Profile published.',
		'item_published_privately' => 'Profile published privately.',
		'item_reverted_to_draft' => 'Profile reverted to draft.',
		'item_scheduled' => 'Profile scheduled.',
		'item_updated' => 'Profile updated.',
		'item_link' => 'Profile Link',
		'item_link_description' => 'A link to a profile.',
	),
	'public' => true,
	'show_in_rest' => true,
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'trackbacks',
		3 => 'editor',
		4 => 'excerpt',
		5 => 'revisions',
		6 => 'page-attributes',
		7 => 'thumbnail',
		8 => 'custom-fields',
		9 => 'post-formats',
	),
	'taxonomies' => array(
		0 => 'category',
		1 => 'post_tag',
	),
	'delete_with_user' => false,
) );
}
















function register_acf_fields_general() {
    $settings = get_verified_profile_settings();
    $singular = $settings['singular'];
    $plural   = $settings['plural'];
    $slug     = $settings['slug'];
    $domain   = parse_url(home_url(), PHP_URL_HOST);

    // Define each group in an array for iteration
    $groups = [
        // 1) Post - Verified Profile - Admin
        [
            'key'       => 'group_post_' . $slug . '_admin',
            'title'     => "Post - {$singular} - Admin",
            'fields'    => [
                [
                    'key'           => 'field_' . $slug . '_profiles',
                    'label'         => $plural,
                    'name'          => 'profiles',
                    'type'          => 'repeater',
                    'layout'        => 'row',
                    'button_label'  => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields'    => [
                        [
                            'key'           => 'field_' . $slug . '_profile',
                            'label'         => $singular,
                            'name'          => 'profile',
                            'type'          => 'post_object',
                            'post_type'     => [$slug],
                            'return_format' => 'id',
                            'ui'            => 1,
                        ],
                    ],
                ],
                [
                    'key'           => 'field_' . $slug . '_pending_profiles',
                    'label'         => 'Pending ' . $plural,
                    'name'          => 'pending_profiles',
                    'type'          => 'repeater',
                    'layout'        => 'table',
                    'button_label'  => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields'    => [
                        ['key'=>'field_pending_name','label'=>'Name','name'=>'name','type'=>'text'],
                        ['key'=>'field_pending_type','label'=>'Profile Type','name'=>'type','type'=>'select','choices'=>['person'=>'Person','organization'=>'Organization']],
                        ['key'=>'field_pending_url','label'=>'URL','name'=>'url','type'=>'text'],
                    ],
                ],
            ],
            'location'  => [
                [['param'=>'post_type','operator'=>'==','value'=>'post']],
                [['param'=>'current_user_role','operator'=>'==','value'=>'administrator']],
            ],
        ],
        // 2) Profile - Admin
        [
            'key'       => 'group_' . $slug . '_admin',
            'title'     => "{$singular} - Admin",
            'fields'    => [
                ['key'=>'field_contributor_profile','label'=>'Contributor Profile','name'=>'contributor_profile','type'=>'user','return_format'=>'id'],
                ['key'=>'field_schema_markup','label'=>'Schema Markup','name'=>'schema_markup','type'=>'textarea'],
                ['key'=>'field_post_id','label'=>'Post ID','name'=>'post_id','type'=>'text'],
                ['key'=>'field_google_knowledge_graph_id','label'=>'Google Knowledge Graph ID','name'=>'google_knowledge_graph_id','type'=>'text'],
                ['key'=>'field_is_council_member','label'=>'Is Council Member','name'=>'is_council_member','type'=>'true_false'],
                ['key'=>'field_is_contributor','label'=>'Is Contributor','name'=>'is_contributor','type'=>'true_false'],
                ['key'=>'field_external_id','label'=>'External ID','name'=>'external_id','type'=>'text'],
            ],
            'location'  => [[['param'=>'post_type','operator'=>'==','value'=>$slug],['param'=>'current_user_role','operator'=>'==','value'=>'administrator']]],
        ],
        // 3) Profile - Person - Public
        [
            'key'       => 'group_' . $slug . '_person_public',
            'title'     => "{$singular} - Person - Public",
            'fields'    => [
                [
                    'key'           => 'field_organizations_founded',
                    'label'         => 'Organizations Founded',
                    'name'          => 'organizations_founded',
                    'type'          => 'repeater',
                    'instructions'  => sprintf('Select a %s. Contact <a href="mailto:verified@%1$s">verified@%1$s</a> if you don\'t see your organization.', $domain),
                    'layout'        => 'table',
                    'button_label'  => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields'    => [
                        ['key'=>'field_organization','label'=>'Organization','name'=>'organization','type'=>'post_object','post_type'=>[$slug],'post_status'=>['publish'],'return_format'=>'object','ui'=>1],
                    ],
                ],
                [
                    'key'           => 'field_books',
                    'label'         => 'Books',
                    'name'          => 'books',
                    'type'          => 'repeater',
                    'layout'        => 'table',
                    'button_label'  => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields'    => [
                        ['key'=>'field_book_title','label'=>'Title','name'=>'title','type'=>'text'],
                        ['key'=>'field_book_cover','label'=>'Cover','name'=>'cover','type'=>'image','return_format'=>'array','preview_size'=>'medium'],
                    ],
                ],
                ['key'=>'field_personal_info','label'=>'Personal Information','name'=>'personal','type'=>'group','layout'=>'block','sub_fields'=>[
                    ['key'=>'field_location_born','label'=>'Location Born','name'=>'location_born','type'=>'group','layout'=>'block','sub_fields'=>[
                        ['key'=>'field_location_name_born','label'=>'Name','name'=>'name','type'=>'text'],
                        ['key'=>'field_location_wikipedia_born','label'=>'Wikipedia URL','name'=>'wikipedia_url','type'=>'text'],
                    ]],
                    ['key'=>'field_current_residence','label'=>'Current Residence','name'=>'current_residence','type'=>'group','layout'=>'block','sub_fields'=>[
                        ['key'=>'field_residence_name','label'=>'Name','name'=>'name','type'=>'text'],
                        ['key'=>'field_residence_wikipedia','label'=>'Wikipedia URL','name'=>'wikipedia_url','type'=>'text'],
                    ]],
                    ['key'=>'field_marital_status','label'=>'Marital Status','name'=>'marital_status','type'=>'select','choices'=>['single'=>'Single','married'=>'Married','divorced'=>'Divorced','other'=>'Other']],
                    ['key'=>'field_children','label'=>'Children','name'=>'children','type'=>'text','instructions'=>'Leave empty to hide from profile.'],
                    ['key'=>'field_education','label'=>'Education','name'=>'education','type'=>'repeater','layout'=>'table','button_label'=>'Add Row','rows_per_page'=>20,'sub_fields'=>[
                        ['key'=>'field_school','label'=>'School','name'=>'school','type'=>'text','instructions'=>'School name (ex: University of Miami)'],
                        ['key'=>'field_degree','label'=>'Degree','name'=>'degree','type'=>'text','instructions'=>'Degree type (ex: BS)'],
                        ['key'=>'field_education_wikipedia','label'=>'Wikipedia URL','name'=>'wikipedia_url','type'=>'text','instructions'=>'Wikipedia url of the school (ex: https://en.wikipedia.org/wiki/University_of_Miami)'],
                    ]],
                    ['key'=>'field_gender','label'=>'Gender','name'=>'gender','type'=>'select','choices'=>['female'=>'Female','male'=>'Male','other'=>'Other','na'=>'Do Not Show Publicly']],
                ]],
            ],
            'location'  => [[['param'=>'post_type','operator'=>'==','value'=>$slug],['param'=>'post_category','operator'=>'==','value'=>'category:person']]],
        ],
        // 4) User - Profile Manager
        [
            'key'       => 'group_user_profile_manager',
            'title'     => 'User - Profile Manager',
            'fields'    => [
                ['key'=>'field_notification_emails','label'=>'Notification Emails','name'=>'notification_emails','type'=>'repeater','layout'=>'table','button_label'=>'Add Row','rows_per_page'=>20,'sub_fields'=>[
                    ['key'=>'field_notification_email','label'=>'Email','name'=>'email','type'=>'text'],
                ]],
            ],
            'location'  => [[['param'=>'current_user_role','operator'=>'==','value'=>'verified_profile_manager'],['param'=>'user_form','operator'=>'==','value'=>'all']],[['param'=>'current_user_role','operator'=>'==','value'=>'administrator'],['param'=>'user_form','operator'=>'==','value'=>'all']]],
        ],
        // 5) User - Verified Profile Manager - Admin
        [
            'key'       => 'group_user_verified_profile_manager_admin',
            'title'     => 'User - Verified Profile Manager - Admin',
            'fields'    => [
                ['key'=>'field_unclaimed_profiles','label'=>'Unclaimed '.$plural,'name'=>'unclaimed_profiles','type'=>'repeater','layout'=>'table','button_label'=>'Add Row','rows_per_page'=>20,'sub_fields'=>[
                    ['key'=>'field_unclaimed_profile','label'=>$singular,'name'=>'profile','type'=>'post_object','post_type'=>[$slug],'return_format'=>'id','ui'=>1],
                ]],
                ['key'=>'field_new_entity_email','label'=>'New Entity Email','name'=>'new_entity_email','type'=>'group','instructions'=>'{first_name}<br />{list_unclaimed_profiles}<br />{featured_profile}<br />{featured_profile_name}<br />{featured_profile_link}<br />{credentials_dashboard}<br />','sub_fields'=>[
                    ['key'=>'field_new_entity_subject','label'=>'Subject','name'=>'subject','type'=>'text'],
                    ['key'=>'field_new_entity_message','label'=>'Message','name'=>'message','type'=>'wysiwyg','tabs'=>'all','toolbar'=>'full','media_upload'=>1],
                ]],
                ['key'=>'field_entity_summary_email','label'=>'Entity Summary Email','name'=>'entity_summary_email','type'=>'group','sub_fields'=>[
                    ['key'=>'field_entity_summary_subject','label'=>'Subject','name'=>'subject','type'=>'text'],
                    ['key'=>'field_entity_summary_message','label'=>'Message','name'=>'message','type'=>'wysiwyg','tabs'=>'all','toolbar'=>'full','media_upload'=>1],
                ]],
                ['key'=>'field_welcome_email','label'=>'Welcome Email','name'=>'welcome_email','type'=>'group','sub_fields'=>[
                    ['key'=>'field_welcome_subject','label'=>'Subject','name'=>'subject','type'=>'text'],
                    ['key'=>'field_welcome_message','label'=>'Message','name'=>'message','type'=>'wysiwyg','tabs'=>'all','toolbar'=>'full','media_upload'=>1],
                ]],
                ['key'=>'field_password','label'=>'Password','name'=>'password','type'=>'text'],
                ['key'=>'field_price_verified_profile','label'=>'Price Verified Profile','name'=>'price_verified_profile','type'=>'text','default_value'=>'19.99'],
                ['key'=>'field_price_leadership_council','label'=>'Price Leadership Council','name'=>'price_leadership_council','type'=>'text'],
                ['key'=>'field_is_council_member2','label'=>'Is Council Member','name'=>'is_council_member','type'=>'true_false'],
                ['key'=>'field_is_contributor2','label'=>'Is Contributor','name'=>'is_contributor','type'=>'true_false'],
            ],
            'location'  => [[['param'=>'current_user_role','operator'=>'==','value'=>'administrator'],['param'=>'user_role','operator'=>'==','value'=>'all']]],
        ],
    ];

    // Register each group
    foreach ($groups as $grp) {
        acf_add_local_field_group($grp);
    }
}
















/*

function register_acf_fields_general()
{
	acf_add_local_field_group( array(
	'key' => 'group_66b7bdf713e77',
	'title' => 'Post - Verified Profile - Admin',
	'fields' => array(
		array(
			'key' => 'field_656c17469ad33',
			'label' => 'Profiles',
			'name' => 'profiles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_656c17629ad34',
					'label' => 'Profile',
					'name' => 'profile',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'profile',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_656c17469ad33',
				),
			),
		),
		array(
			'key' => 'field_65852128a382d',
			'label' => 'Pending Profiles',
			'name' => 'pending_profiles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_658521e7a382e',
					'label' => 'Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_65852128a382d',
				),
				array(
					'key' => 'field_658521f3a382f',
					'label' => 'Profile Type',
					'name' => 'type',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'person' => 'Person',
						'organization' => 'Organization',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_65852128a382d',
				),
				array(
					'key' => 'field_6585224da3830',
					'label' => 'URL',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_65852128a382d',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_656ea6b4d7088',
	'title' => 'Profile - Admin',
	'fields' => array(
		array(
			'key' => 'field_6588affed09cc',
			'label' => 'Contributor Profile',
			'name' => 'contributor_profile',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6594fbe18a8d8',
			'label' => 'Schema Markup',
			'name' => 'schema_markup',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6599cd05bae59',
			'label' => 'Post ID',
			'name' => 'post_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65a369536c734',
			'label' => 'Google Knowledge Graph ID',
			'name' => 'google_knowledge_graph_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65a8ae45f6912',
			'label' => 'Is Council Member',
			'name' => 'is_council_member',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_65b0b66f0e30e',
			'label' => 'Is Contributor',
			'name' => 'is_contributor',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_65b0b6600e30d',
			'label' => 'External ID',
			'name' => 'external_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profile',
			),
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

$domain = parse_url( home_url(), PHP_URL_HOST );


	acf_add_local_field_group( array(
	'key' => 'group_656eb036374de',
	'title' => 'Profile - Person - Public',
	'fields' => array(
		array(
			'key' => 'field_656e8459286e2',
			'label' => 'Organizations Founded',
			'name' => 'organizations_founded',
			'aria-label' => '',
			'type' => 'repeater',
            'instructions'=> sprintf(
                'Select a Verified Organization. Contact <a href="mailto:verified@%s">verified@%s</a> if you don\'t see your organization.',
                $domain,
                $domain
            ),'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_656e86ac286e3',
					'label' => 'Organization',
					'name' => 'organization',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'profile',
					),
					'post_status' => array(
						0 => 'publish',
					),
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_656e8459286e2',
				),
			),
		),
		array(
			'key' => 'field_656c15b689d35',
			'label' => 'Books',
			'name' => 'books',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_656c15c389d36',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_656c15b689d35',
				),
				array(
					'key' => 'field_656c15d489d37',
					'label' => 'Cover',
					'name' => 'cover',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_656c15b689d35',
				),
			),
		),
		array(
			'key' => 'field_656e82e843a16',
			'label' => 'Personal Information',
			'name' => 'personal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6588d56dfcff6',
					'label' => 'Location Born',
					'name' => 'location_born',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6588d585fcff7',
							'label' => 'Name',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6588d58efcff8',
							'label' => 'Wikipedia URL',
							'name' => 'wikipedia_url',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_6588d5acfcff9',
					'label' => 'Current Residence',
					'name' => 'current_residence',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6588d5acfcffa',
							'label' => 'Name',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6588d5acfcffb',
							'label' => 'Wikipedia URL',
							'name' => 'wikipedia_url',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_656e830c43a19',
					'label' => 'Marital Status',
					'name' => 'marital_status',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						':' => ':',
						'single' => 'Single',
						'married' => 'Married',
						'divorced' => 'Divorced',
						'other' => 'Other',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_656e831a43a1a',
					'label' => 'Children',
					'name' => 'children',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Leave empty to hide from profile.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6588d47563ecc',
					'label' => 'Education',
					'name' => 'education',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6588d48763ecd',
							'label' => 'School',
							'name' => 'school',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'School name (ex: University of Miami)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6588d47563ecc',
						),
						array(
							'key' => 'field_6588d49763ece',
							'label' => 'Degree',
							'name' => 'degree',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Degree type (ex: BS)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6588d47563ecc',
						),
						array(
							'key' => 'field_6588d49f63ecf',
							'label' => 'Wikipedia URL',
							'name' => 'wikipedia_url',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Wikipedia url of the school (ex: https://en.wikipedia.org/wiki/University_of_Miami)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6588d47563ecc',
						),
					),
				),
				array(
					'key' => 'field_6591f203bbb3a',
					'label' => 'Gender',
					'name' => 'gender',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'female' => 'Female',
						'male' => 'Male',
						'other' => 'Other',
						'na' => 'Do Not Show Publicly',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profile',
			),
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:person',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_65a8b25062d91',
	'title' => 'User - Profile Manager',
	'fields' => array(
		array(
			'key' => 'field_65874f87985c0',
			'label' => 'Notification Emails',
			'name' => 'notification_emails',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_65874f90985c1',
					'label' => 'Email',
					'name' => 'email',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_65874f87985c0',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'verified_profile_manager',
			),
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
			),
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_658602c9eaa49',
	'title' => 'User - Verified Profile Manager - Admin',
	'fields' => array(
		array(
			'key' => 'field_659a5d6c40f5a',
			'label' => 'Unclaimed Profiles',
			'name' => 'unclaimed_profiles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'This repeater will ONLY show CPT: "profiles" from the author slug "unclaimed". Don\'t want multiple people having ownership of the same entity.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_659a5dbd40f5b',
					'label' => 'Profile',
					'name' => 'profile',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'profile',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_659a5d6c40f5a',
				),
			),
		),
		array(
			'key' => 'field_6586031ac6afc',
			'label' => 'New Entity Email',
			'name' => 'new_entity_email',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '{first_name}<br />
{list_unclaimed_profiles}<br />
{featured_profile}<br />
{featured_profile_name}<br />
{featured_profile_link}<br />
{credentials_dashboard}<br />',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_65860330c6afd',
					'label' => 'Subject',
					'name' => 'subject',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6586033cc6afe',
					'label' => 'Message',
					'name' => 'message',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_659decb4802d7',
			'label' => 'Entity Summary Email',
			'name' => 'entity_summary_email',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_659decb4802d8',
					'label' => 'Subject',
					'name' => 'subject',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_659decb4802d9',
					'label' => 'Message',
					'name' => 'message',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_658602dc4ea03',
			'label' => 'Welcome Email',
			'name' => 'welcome_email',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_658602ee4ea04',
					'label' => 'Subject',
					'name' => 'subject',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_658602fa4ea05',
					'label' => 'Message',
					'name' => 'message',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_659f267203e55',
			'label' => 'Password',
			'name' => 'password',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65a4594ecdee4',
			'label' => 'Price Verified Profile',
			'name' => 'price_verified_profile',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '19.99',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65a45a45cdee7',
			'label' => 'Price Leadership Council',
			'name' => 'price_leadership_council',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65a8aeaa48c6f',
			'label' => 'Is Council Member',
			'name' => 'is_council_member',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_65b0b7be9876c',
			'label' => 'Is Contributor',
			'name' => 'is_contributor',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
			),
			array(
				'param' => 'user_role',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
}
*/


